### ISSUE TITLE
make pictures and their scores importable with php

### ISSUE THREAD

**Issue by AJM-1** [computationalmystic/RJI-group23#2]
write the code that imports the files in the selected directory and displays the necessary information.
When the page loads, the pictures' information will need to be loaded from the server with php in order to display them to the user.
![main screen](https://user-images.githubusercontent.com/44102621/56988886-b59f8280-6b56-11e9-829a-664fba917326.png)

**Comment by sgoggins** [comment]
Why would the scores need to be imported? 

A little more description here will help.

**Comment by AJM-1** [comment]
the div now imports all the photos, but does not read their scores. This has to wait until analyze.php is working as shown in a different issue.

**Comment by AJM-1** [comment]
scores now show for each picture
